FROM golang:1.23-alpine AS builder

WORKDIR /build

RUN apk add --no-cache git gcc musl-dev

COPY go.mod go.sum ./
RUN go mod download

COPY . .


RUN CGO_ENABLED=1 GOOS=linux go build -o payflow-server ./cmd/server

FROM alpine:latest

WORKDIR /app

RUN apk add --no-cache ca-certificates tzdata sqlite

COPY --from=builder /build/payflow-server .
COPY --from=builder /build/.env .
COPY --from=builder /build/monitoring ./monitoring

RUN chmod +x /app/payflow-server

EXPOSE 8080

CMD ["./payflow-server"]